# @package _group_

agent:
    _target_: algorithms.sac.SAC
    obs_dim: 8
    action_dim: 2
    actor_cfg: ${algo.actor}
    critic_cfg: ${algo.critic}
    discount: 0.9
    reward_scale: .1
    policy_lr: 3e-4
    qf_lr: 3e-4
    soft_target_tau: 1e-2
    use_automatic_entropy_tuning: true
    policy_eval_start: 0
    min_q_version: 3
    temp: 1.0
    min_q_weight: 1.0
    use_cql: false
    max_q_backup: false
    deterministic_backup: false
    num_random: 10
    with_lagrange: true
    lagrange_thresh: 2.0
    init_log_alpha_prime: -4.
    factored: ${factored}

actor:
    _target_: algorithms.sac.actor.DiagGaussianActor
    obs_dim: ${algo.agent.obs_dim}
    action_dim: ${algo.agent.action_dim}
    hidden_dim: 256
    hidden_depth: 2
    log_std_bounds: [-5, 2]

critic:
    _target_: algorithms.sac.critic.FactoredCritic
    obs_dim: ${algo.agent.obs_dim}
    action_dim: ${algo.agent.action_dim}
    hidden_dim: 256
    hidden_depth: 2
