defaults:
  - algo: sac

exp_name: ???
checkpoint_freq: 1

gpu: 0 # assuming single GPU
seed: 0
server_port: 2000

use_images: true

factored: false

data_module:
    batch_size: 32
    buffer_size: 1e4
    num_workers: 4
    dataset_paths: 
      - '/zfsauton/datasets/ArgoRL/brianyan/carla_dataset/town01/expert/'
    train_val_split: 0.9
    use_images: ${use_images}
    frame_stack: 1
    populate_size: 1000
    epoch_size: 2000
    train_every_n_steps: 2

environment:
    sample_npc: true
    # num_npc: 60
    scenarios: 'no_crash_dense'
    input_type: 'wp_obs_info_speed_steer_ldist_goal_light'
    const_collision_penalty: 50
    const_light_penalty: 50
    frame_skip: 2
    verbose: 0
    use_images: ${use_images}
    factored: ${factored}

eval_freq: 1
eval_length: 2000
num_eval_episodes: 1

train_offline: false
offline_epochs: 500

train_online: true
online_epochs: 10000


value_model: ???


trainer:
    precision: 16
    gpus: ${gpu}

hydra:
    run:
        dir: /home/scratch/brianyan/outputs/${exp_name}/${now:%Y-%m-%d_%H-%M-%S}
