exp_name: ???
checkpoint_freq: 1

gpu: 0 # assuming single GPU
seed: 0
server_port: 2000

use_images: true

data_module:
    batch_size: 64
    num_workers: 4
    dataset_paths: 
      - '/zfsauton/datasets/ArgoRL/brianyan/carla_dataset/town01/expert/'
      - '/zfsauton/datasets/ArgoRL/brianyan/carla_dataset/town02/expert/'
    use_images: ${use_images}
    val_dataset_idx:
      - 1
    max_train_trajectories: -1
    max_val_trajectories: 15
    horizon_length: 26

agent:
    conv_type: convlstm
    attention_type: bottom_up

eval_freq: 1
eval_length: 1000
num_eval_episodes: 10

num_epochs: 100

trainer:
    precision: 16
    gpus: ${gpu}

hydra:
    run:
        dir: /home/scratch/brianyan/outputs/${exp_name}/${now:%Y-%m-%d_%H-%M-%S}
