model_path: /home/brian/temp/model.th

num_scenarios: 25

use_pid: true
log_dir: /home/brian/temp/logs/
output_dir: /home/brian/temp/logs/
greedy_dir: /home/brian/temp/logs/
pid_dir: /home/brian/temp/logs/
