model_path: /zfsauton/datasets/ArgoRL/jhoang/models/4a22bc18083f46fe8c1805d3c8e825cc/model.th

num_scenarios: 25

use_pid: true
log_dir: /zfsauton/datasets/ArgoRL/jhoang/logs/
output_dir: /zfsauton/datasets/ArgoRL/jhoang/pid_t2/
greedy_dir: /zfsauton/datasets/ArgoRL/jhoang/greedy/ 
pid_dir: /zfsauton/datasets/ArgoRL/jhoang/pid/ 